# Generated by Django 2.1 on 2019-01-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
