# Generated by Django 2.1 on 2019-02-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20190202_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo_carteira',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
