# Generated by Django 2.1 on 2019-03-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_cliente_saldo_carteira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
    ]
