# Generated by Django 2.1 on 2019-05-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_auto_20190301_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_carteira',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='saldo_carteira',
        ),
    ]
