# Generated by Django 2.1 on 2019-02-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0003_auto_20190207_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome'),
        ),
    ]
