# Generated by Django 2.1 on 2019-02-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0004_auto_20190207_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='private_key',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Chave Privada'),
        ),
    ]
