# Generated by Django 2.1 on 2019-03-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0005_auto_20190226_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='id_token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
