# Generated by Django 2.1 on 2019-03-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0006_carteira_id_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_token', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='id_token',
        ),
        migrations.AddField(
            model_name='carteiratoken',
            name='id_carteira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteira.Carteira'),
        ),
    ]
