# Generated by Django 2.1 on 2019-04-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0007_auto_20190330_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteiratoken',
            name='saldo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
