# Generated by Django 2.1 on 2019-04-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0008_carteiratoken_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteiratoken',
            name='simbolo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='carteiratoken',
            name='token',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
