# Generated by Django 2.1 on 2019-05-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0009_auto_20190406_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteiratoken',
            name='contract',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
