# Generated by Django 2.1 on 2019-01-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('password', models.CharField(max_length=100, verbose_name='Senha')),
                ('salt', models.CharField(max_length=10, verbose_name='Salt')),
                ('level', models.CharField(max_length=100, verbose_name='Nivel')),
                ('access', models.IntegerField(blank=True, null=True)),
                ('ip_last', models.GenericIPAddressField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Criando em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
