# Generated by Django 2.1 on 2019-01-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20190117_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='salt',
        ),
    ]
