# Generated by Django 2.1 on 2019-01-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20190130_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Esta ativo'),
        ),
    ]
