# Generated by Django 2.1 on 2019-02-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0005_auto_20190125_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criando em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('wallet_private_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('wallet_address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('solidity_version', models.CharField(blank=True, default='0.4.25', max_length=10, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criando em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='contratactions',
            name='id_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.Contrato'),
        ),
    ]
