# Generated by Django 2.1 on 2019-02-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratactions',
            name='id_cliente',
        ),
    ]
