# Generated by Django 2.1 on 2019-02-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_remove_contratactions_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='solidity_version',
            field=models.CharField(blank=True, default='>=0.4.21 <0.6.0', max_length=20, null=True),
        ),
    ]
