# Generated by Django 2.1 on 2019-02-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_auto_20190214_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='abi',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
