# Generated by Django 2.1 on 2019-03-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0007_auto_20190228_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='contract_address',
            new_name='hash_address',
        ),
        migrations.RemoveField(
            model_name='contratactions',
            name='number',
        ),
        migrations.AddField(
            model_name='contratactions',
            name='blocknumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contratactions',
            name='contract_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratactions',
            name='from_adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratactions',
            name='gasUsed',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contratactions',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contratactions',
            name='to_adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratactions',
            name='transactionHash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
