# Generated by Django 2.1 on 2019-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0008_auto_20190301_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='wallet_private_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
