# Generated by Django 2.1 on 2019-03-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0010_auto_20190301_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=15, null=True)),
                ('simbolo', models.CharField(blank=True, max_length=5, null=True)),
                ('quantidade', models.CharField(blank=True, max_length=5, null=True)),
                ('digitos', models.CharField(blank=True, max_length=5, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criando em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.Contrato')),
            ],
        ),
    ]
