# Generated by Django 2.1 on 2019-03-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0011_contrattoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattoken',
            name='contract_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
