# Generated by Django 2.1 on 2019-03-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0013_auto_20190329_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='id_carteira',
            field=models.IntegerField(),
        ),
    ]
