# Generated by Django 2.1 on 2019-04-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0014_auto_20190330_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrattoken',
            name='contract_address',
        ),
        migrations.AddField(
            model_name='contrato',
            name='contract_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='solidity_version',
            field=models.CharField(blank=True, default='>=0.4.25 <0.6.0', max_length=20, null=True),
        ),
    ]
