# Generated by Django 2.1 on 2019-04-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0015_auto_20190406_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
